# ~/.config/hypr/autostart.conf
#                     dP                       dP                       dP   
#                     88                       88                       88   
# .d8888b. dP    dP d8888P .d8888b. .d8888b. d8888P .d8888b. 88d888b. d8888P 
# 88'  `88 88    88   88   88'  `88 Y8ooooo.   88   88'  `88 88'  `88   88   
# 88.  .88 88.  .88   88   88.  .88       88   88   88.  .88 88         88   
# `88888P8 `88888P'   dP   `88888P' `88888P'   dP   `88888P8 dP         dP   
# =============================================
$cursor = hyprctl setcursor "Nordic-cursors" 20
# =============================================
exec-once = waybar      #taskbar
exec-once = swww-daemon #wallpaper daemon, to start it use "hyprctl dispatch exec swww-daemon"
exec-once = $cursor     #setting cursor
exec-once = pipewire    #start audio 
exec-once = xwaylandvideobridge #start bridge for discord or obs streaming                                                                                                                   
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = xdg-desktop-portal-hyprland
exec-once = xdg-desktop-portal
# =======================================
exec-once = v2rayn          # vpn 
#exec-once = hyprtasking     # workspaces 
exec-once = udiskie         # flashdrive automount    
exec-once = blueman-applet  # bluetooth
exec-once = $HOME/scripts/hypr/workspace_listener.sh