# Here is display settings, touch it if you know what you do
# ~/.config/hypr/Display.conf

windowrule{
name= floating
match:class = float
size = 800 600
animation = popin 
float = on
center = on
}
windowrule{
name = Pipewire 
match:class = org.pipewire.Helvum
size = 1100 850
center = on
animation = popin
float = on
pin = on
}
windowrule{
name = HyprshotGUI
match:title = Hyprshot
match:class = python3
center = on 
pin = on
animation = popin
float = on
stay_focused = on
size = 350 300
}
windowrule{
name = telegram
match:class = org.telegram.desktop
float = on
pin = on 
move = 0 0
size = 600 1070
animation = slide
}
windowrule{
name = discord
match:class = discord  
float = on
pin = on 
move = 0 0
size = 415 700

}
windowrule{
name = pip
match:class = firefox
match:title = Picture-in-Picture
pin = on
float = on
center = on
move = 0 0
size= 450 250
}
#windowrule{
#name = resizeactive
#match:float = true 
#match:focus = false
#opacity = 0.2
#size = 600 1070
#move = 0 0
#no_blur = on
#no_dim = on
#}
