# https://github.com/raybbian/hyprtasking?tab=readme-ov-file#Installation
bind = , escape, hyprtasking:if_active, hyprtasking:toggle cursor

bind = $mainMod, tab, hyprtasking:toggle, all
bind = $mainMod, w, hyprtasking:toggle, cursor


bind = $mainMod, X, hyprtasking:killhovered

bind = $mainMod SHIFT, left, hyprtasking:move, left
bind = $mainMod SHIFT, down, hyprtasking:move, down
bind = $mainMod SHIFT, up, hyprtasking:move, up
bind = $mainMod SHIFT, right, hyprtasking:move, right

plugin {
    hyprtasking {
        layout = grid

        gap_size = 10
        bg_color = 0xff26233a
        border_size = 4
        exit_on_hovered = false
        warp_on_move_window = 1
        close_overview_on_reload = true

        drag_button = 0x110 # left mouse button
        select_button = 0x111 # right mouse button
        # for other mouse buttons see <linux/input-event-codes.h>

        gestures {
            enabled = true
            move_fingers = 3
            move_distance = 300
            open_fingers = 4
            open_distance = 300
            open_positive = true
        }

        grid {
            rows = 2
            cols = 2
            loop = false
            gaps_use_aspect_ratio = false
        }

        linear {
            height = 400
            scroll_speed = 1.0
            blur = false
        }
    }
}
